name: Release latest

on:
  workflow_dispatch:
    inputs:
      use-nx-cache:
        type: boolean
        description: 'Use NX cache'
        default: true
      publish:
        type: boolean
        description: 'Publish to npm'
        default: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Verify release channel
        run: |
          branch=${GITHUB_REF#refs/heads/}
          if [[ "$branch" != "main" ]]; then
            echo "Error: Branch '$branch' is not a valid release branch. Valid options are: main."
            exit 1
          fi

      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Set up git bot user
        uses: snow-actions/git-config-user@v1.0.0

      - name: Create version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          npx nx affected \
            -t coverage-badge \
            -t version \
            -c release \
            --base=latest \
            --skipNxCache ${{ !inputs.use-nx-cache }} \
            --dry-run ${{ env.ACT || 'false'  }} \
            --parallel 1

      - name: Tag latest
        shell: bash
        run: git tag -f latest

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          tags: true
