name: Release maintenance

on:
  workflow_dispatch:
    inputs:
      use-nx-cache:
        type: boolean
        description: 'Use NX cache'
        default: true
      publish:
        type: boolean
        description: 'Publish to npm'
        default: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Verify release channel
        id: get-channel
        run: |
          branch=${GITHUB_REF#refs/heads/}
          if [[ ! "$branch" =~ ^[a-zA-Z0-9_-]+@[0-9]+\.([0-9]+|x)\.x$ ]]; then
            echo "Error: Branch $branch is not a maintenance branch"
            exit 1
          fi          
          echo "channel=$branch" >> $GITHUB_OUTPUT

      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Set up git bot user
        uses: snow-actions/git-config-user@v1.0.0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        if: ${{ !env.ACT }}
        uses: nrwl/nx-set-shas@v4

      - name: Generate coverage badge
        run: |
          npx nx affected -t coverage-badge --skipNxCache=${{ !inputs.use-nx-cache }}
          git add .

      - name: Create version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx nx release version

      - name: Get the tag that was just created
        id: get-latest-tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          semver=${latest_tag#*@}
          echo "tag=$semver" >> $GITHUB_OUTPUT

      - name: Create changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx nx release changelog ${{ steps.get-latest-tag.outputs.tag }} --dry-run=${{ env.ACT || 'false'  }}

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Publish
        if: ${{ inputs.publish }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          npx nx release publish \
            --tag ${{ steps.get-channel.outputs.channel }} \
            --skipNxCache=${{ !inputs.use-nx-cache }} \
            --dry-run=${{ env.ACT || 'false'  }}
