name: Release maintenance

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: 'Maintenance branch to release from (e.g., package-name@1.x or package-name@1.0.x)'
        required: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Set up git bot user
        uses: snow-actions/git-config-user@v1.0.0

      - name: Generate coverage badge
        run: npx nx run-many -t coverage-badge

      - name: Validate branch input
        run: |
          branch=${{ github.event.inputs.branch }}
          if [[ ! "$branch" =~ ^[a-zA-Z0-9-_]+@[0-9]+\.[0-9]*\.?x$ ]]; then
            echo "Invalid branch format: $branch"
            exit 1
          fi

      - name: Create maintenance release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx nx release --skip-publish

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: npx nx release publish --tag ${{ github.event.inputs.branch }}
