name: Release pre-release

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: 'Pre-release branch to release from'
        required: true
        options:
          - alpha
          - beta
          - next

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Set up git bot user
        uses: snow-actions/git-config-user@v1.0.0

      - name: Determine release channel
        id: get-channel
        run: |
          branch=$(echo ${GITHUB_REF#refs/heads/})
          echo "channel=$branch" >> $GITHUB_OUTPUT

      - name: Create pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx nx release version prerelease --preid=${{ steps.get-channel.outputs.channel }} --git-tag

      - name: Check if a new tag was created
        id: check-tag
        run: |
          if git tag --points-at HEAD | grep -q .; then
            echo "created=true" >> $GITHUB_OUTPUT
          else
            echo "created=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish
        if: steps.check-tag.outputs.created == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: npx nx release publish --tag ${{ steps.get-channel.outputs.channel }}
